# Generated by Django 5.1.1 on 2024-09-28 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.TextField(verbose_name="Company name")),
                ("customer_city", models.TextField(verbose_name="City")),
                ("customer_address", models.TextField(verbose_name="Address")),
            ],
            options={
                "verbose_name": "Description counterparty",
                "verbose_name_plural": "Description counterparty",
                "db_table": "Customers",
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("manufacturer", models.TextField(verbose_name="Manufacturer")),
                ("model", models.TextField(verbose_name="Model")),
            ],
            options={
                "verbose_name": "Available Devices",
                "verbose_name_plural": "Available Devices",
                "db_table": "Devices",
            },
        ),
        migrations.CreateModel(
            name="DeviceInField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.TextField(verbose_name="Serial number")),
                ("owner_status", models.TextField(verbose_name="Affiliation status")),
                (
                    "analyzer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="orders_app.device",
                        verbose_name="Equipment",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="orders_app.customer",
                        verbose_name="Customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Devices in field",
                "verbose_name_plural": "Devices in field",
                "db_table": "Devices_in_fields",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_description", models.TextField(verbose_name="Description")),
                (
                    "created_dt",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "last_updated_dt",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last update"
                    ),
                ),
                (
                    "order_status",
                    models.TextField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("in progress", "In progress"),
                            ("need info", "Need info"),
                        ],
                        verbose_name="Order status",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="orders_app.device",
                        verbose_name="Device",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orders",
                "verbose_name_plural": "Orders",
                "db_table": "Orders",
            },
        ),
    ]
