# Generated by Django 5.1.1 on 2024-09-30 09:45

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="customer_email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="customer",
            name="customer_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+00000000000",
                max_length=128,
                region=None,
                verbose_name="Phone number",
            ),
        ),
    ]
