# Generated by Django 5.1.1 on 2024-10-04 08:32

import datetime
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0002_customer_customer_email_customer_customer_phone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="customer_address",
            new_name="address",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="customer_city",
            new_name="city",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="customer_email",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="customer_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="customer_phone",
        ),
        migrations.RemoveField(
            model_name="deviceinfield",
            name="analyzer",
        ),
        migrations.AddField(
            model_name="customer",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default=None,
                max_length=128,
                null=True,
                region=None,
                verbose_name="Phone number",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="date_entered",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date Entered"
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="date_returned",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date Returned"
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="is_in_field",
            field=models.BooleanField(default=False, verbose_name="Is in Field"),
        ),
        migrations.AddField(
            model_name="deviceinfield",
            name="field_device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="orders_app.device",
                verbose_name="Device",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="last_updated_dt",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2024, 10, 4, 11, 32, 4, 710982),
                null=True,
                verbose_name="Last update",
            ),
        ),
    ]
