# Generated by Django 5.1.1 on 2024-10-04 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0003_rename_customer_address_customer_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="last_updated_dt",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2024, 10, 4, 16, 18, 22, 892239),
                null=True,
                verbose_name="Last update",
            ),
        ),
    ]
