# Generated by Django 5.1.1 on 2024-10-04 13:57

import datetime
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0004_alter_order_last_updated_dt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default=None,
                max_length=128,
                null=True,
                region="UA",
                verbose_name="Phone number",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="last_updated_dt",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2024, 10, 4, 16, 57, 14, 533652),
                null=True,
                verbose_name="Last update",
            ),
        ),
    ]
