# Generated by Django 5.1.1 on 2024-10-09 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0005_alter_customer_phone_alter_order_last_updated_dt"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="name",
            new_name="company_name",
        ),
        migrations.AddField(
            model_name="customer",
            name="registration_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 10, 9, 8, 11, 17, 345967),
                verbose_name="Registration date",
            ),
        ),
        migrations.AlterField(
            model_name="deviceinfield",
            name="owner_status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("in_use", "In Use"),
                    ("under_repair", "Under Repair"),
                    ("returned", "Returned"),
                ],
                default="available",
                max_length=20,
                verbose_name="Device Status",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="last_updated_dt",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2024, 10, 9, 8, 11, 17, 346966),
                null=True,
                verbose_name="Last update",
            ),
        ),
    ]
