# Generated by Django 5.1.1 on 2024-10-09 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0006_rename_name_customer_company_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="registration_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 10, 9, 17, 4, 0, 114667),
                verbose_name="Registration date",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="last_updated_dt",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2024, 10, 9, 17, 4, 0, 114667),
                null=True,
                verbose_name="Last update",
            ),
        ),
    ]
